meta_product_name: "Superclosing"
meta_title: "Superclosing - la façon la plus simple et la plus rapide de gérer votre levée de fonds"
meta_description: "Une plateforme juridique complète pour vous accompagner dans vos levées de fonds"
meta_image: "cover.png"
twitter_account: "@MathieuRibot"
